# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _vci
else:
    import _vci

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

SHARED_PTR_DISOWN = _vci.SHARED_PTR_DISOWN
class _vci_exception(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, app_tag, info, path):
        _vci._vci_exception_swiginit(self, _vci.new__vci_exception(app_tag, info, path))
    __swig_destroy__ = _vci.delete__vci_exception

    def app_tag(self):
        return _vci._vci_exception_app_tag(self)

    def info(self):
        return _vci._vci_exception_info(self)

    def path(self):
        return _vci._vci_exception_path(self)

    def what(self):
        return _vci._vci_exception_what(self)

# Register _vci_exception in _vci:
_vci._vci_exception_swigregister(_vci_exception)
class Config(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def set(self, input):
        return _vci.Config_set(self, input)

    def check(self, input):
        return _vci.Config_check(self, input)

    def get(self):
        return _vci.Config_get(self)
    __swig_destroy__ = _vci.delete_Config

    def __init__(self):
        if self.__class__ == Config:
            _self = None
        else:
            _self = self
        _vci.Config_swiginit(self, _vci.new_Config(_self, ))
    def __disown__(self):
        self.this.disown()
        _vci.disown_Config(self)
        return weakref.proxy(self)

# Register Config in _vci:
_vci.Config_swigregister(Config)
class State(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def get(self):
        return _vci.State_get(self)
    __swig_destroy__ = _vci.delete_State

    def __init__(self):
        if self.__class__ == State:
            _self = None
        else:
            _self = self
        _vci.State_swiginit(self, _vci.new_State(_self, ))
    def __disown__(self):
        self.this.disown()
        _vci.disown_State(self)
        return weakref.proxy(self)

# Register State in _vci:
_vci.State_swigregister(State)
class Method(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, input):
        return _vci.Method___call__(self, input)
    __swig_destroy__ = _vci.delete_Method

    def __init__(self):
        if self.__class__ == Method:
            _self = None
        else:
            _self = self
        _vci.Method_swiginit(self, _vci.new_Method(_self, ))
    def __disown__(self):
        self.this.disown()
        _vci.disown_Method(self)
        return weakref.proxy(self)

# Register Method in _vci:
_vci.Method_swigregister(Method)
class MethodMeta(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, meta, input):
        return _vci.MethodMeta___call__(self, meta, input)
    __swig_destroy__ = _vci.delete_MethodMeta

    def __init__(self):
        if self.__class__ == MethodMeta:
            _self = None
        else:
            _self = self
        _vci.MethodMeta_swiginit(self, _vci.new_MethodMeta(_self, ))
    def __disown__(self):
        self.this.disown()
        _vci.disown_MethodMeta(self)
        return weakref.proxy(self)

# Register MethodMeta in _vci:
_vci.MethodMeta_swigregister(MethodMeta)
class Subscriber(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __call__(self, input):
        return _vci.Subscriber___call__(self, input)
    __swig_destroy__ = _vci.delete_Subscriber

    def __init__(self):
        if self.__class__ == Subscriber:
            _self = None
        else:
            _self = self
        _vci.Subscriber_swiginit(self, _vci.new_Subscriber(_self, ))
    def __disown__(self):
        self.this.disown()
        _vci.disown_Subscriber(self)
        return weakref.proxy(self)

# Register Subscriber in _vci:
_vci.Subscriber_swigregister(Subscriber)
class Model(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _vci.Model_swiginit(self, _vci.new_Model(name))
    __swig_destroy__ = _vci.delete_Model

    def config(self, config):
        return _vci.Model_config(self, config)

    def state(self, state):
        return _vci.Model_state(self, state)

    def rpc(self, *args):
        return _vci.Model_rpc(self, *args)

# Register Model in _vci:
_vci.Model_swigregister(Model)
class Component(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, name):
        _vci.Component_swiginit(self, _vci.new_Component(name))

    def run(self):
        return _vci.Component_run(self)

    def wait(self):
        return _vci.Component_wait(self)

    def stop(self):
        return _vci.Component_stop(self)

    def subscribe(self, *args):
        return _vci.Component_subscribe(self, *args)

    def unsubscribe(self, module, notification):
        return _vci.Component_unsubscribe(self, module, notification)

    def model(self, model):
        return _vci.Component_model(self, model)

    def client(self):
        return _vci.Component_client(self)
    __swig_destroy__ = _vci.delete_Component

# Register Component in _vci:
_vci.Component_swigregister(Component)
class RPCCall(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _vci.RPCCall_swiginit(self, _vci.new_RPCCall())
    __swig_destroy__ = _vci.delete_RPCCall

    def output(self):
        return _vci.RPCCall_output(self)

# Register RPCCall in _vci:
_vci.RPCCall_swigregister(RPCCall)
class Subscription(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _vci.Subscription_swiginit(self, _vci.new_Subscription())
    __swig_destroy__ = _vci.delete_Subscription

    def run(self):
        return _vci.Subscription_run(self)

    def cancel(self):
        return _vci.Subscription_cancel(self)

    def coalesce(self):
        return _vci.Subscription_coalesce(self)

    def drop_after_limit(self, limit):
        return _vci.Subscription_drop_after_limit(self, limit)

    def block_after_limit(self, limit):
        return _vci.Subscription_block_after_limit(self, limit)

    def remove_limit(self):
        return _vci.Subscription_remove_limit(self)

# Register Subscription in _vci:
_vci.Subscription_swigregister(Subscription)
class Client(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _vci.Client_swiginit(self, _vci.new_Client())
    __swig_destroy__ = _vci.delete_Client

    def call(self, module, name, input):
        return _vci.Client_call(self, module, name, input)

    def emit(self, module, name, data):
        return _vci.Client_emit(self, module, name, data)

    def config_by_model(self, model):
        return _vci.Client_config_by_model(self, model)

    def state_by_model(self, model):
        return _vci.Client_state_by_model(self, model)

    def subscribe(self, *args):
        return _vci.Client_subscribe(self, *args)

# Register Client in _vci:
_vci.Client_swigregister(Client)

class Exception(__builtin__.Exception, _vci_exception):
	def __init__(self, app_tag, info, path, *args):
		__builtin__.Exception.__init__(self, *args)
		_vci_exception.__init__(self, app_tag, info, path, *args)
	def what(self):
		return _vci_exception.what(self)
	def __repr__(self):
		return self.what()
	def __str__(self):
		return self.what()


